#!/bin/bash
set -x
#set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`

CONFIG=$BASE_DIR/config
source "$CONFIG" 2> /dev/null || {
  CONFIG=$CONFIG.sample
  source "$CONFIG" 2> /dev/null || {
    echo "File \"$CONFIG\" was not found!"
    exit 1
  }
}

DISK=${DISK:-sda}

PUBKEY_FILE=~/.ssh/id_rsa.pub
if ! [ -r $PUBKEY_FILE ]
then
  echo "Please, use ssh-keygen to generate the file $PUBKEY_FILE"
  exit 0
fi

PUBKEY=$(cat $PUBKEY_FILE)

cd "$BASE_DIR"

ssh-keygen -R $VM_IP

# copy your public key, so can ssh without a password later on
ssh -tt -p $VM_SSH_PORT root@$VM_IP "rm -rf ~/.ssh; mkdir -m 700 ~/.ssh; echo $PUBKEY > ~/.ssh/authorized_keys; chmod 600 ~/.ssh/authorized_keys"

# copy install scripts from ./root folder
scp -P $VM_SSH_PORT config config.sample root/* root@$VM_IP:~/

# run the install script remotely
ssh -tt -p $VM_SSH_PORT root@$VM_IP "chmod +x ./{install,chroot}; ./install $DISK"
