#!/bin/bash
set +x
#set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`

CONFIG=$BASE_DIR/config
source "$CONFIG" 2> /dev/null || {
  CONFIG=$CONFIG.sample
  source "$CONFIG" 2> /dev/null || {
    echo "File \"$CONFIG\" was not found!"
    exit 1
  }
}

# grub as a bootloader
grub-install --target=i386-pc --recheck "$1"

# This makes the grub timeout 0, it's faster than 5 :)
sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

# run these following essential service by default
systemctl enable sshd.service
systemctl enable dhcpcd.service
systemctl enable ntpd.service

echo $HOSTNAME > /etc/hostname

# inject vimrc config to default user dir if you like vim
echo -e 'runtime! archlinux.vim\nsyntax on' > /etc/skel/.vimrc

# adding your normal user with additional wheel group so can sudo
useradd -m -G wheel -s /bin/bash $USERNAME

# setting user password
echo $USERNAME:$USERPASS | chpasswd

# adding public key both to root and user for ssh key access
mkdir -m 700 $HOME_DIR/.ssh
mkdir -m 700 /root/.ssh
cp /authorized_keys $HOME_DIR/.ssh/
cp /authorized_keys /root/.ssh
chown -R $USERNAME:$USERNAME $HOME_DIR/.ssh

# adjust your timezone here
ln -f -s /usr/share/zoneinfo/Portugal /etc/localtime
hwclock --systohc

# adjust your name servers here if you don't want to use google
#echo 'name_servers="8.8.8.8 8.8.4.4"' >> /etc/resolvconf.conf

# setting locale
echo en_US.UTF-8 UTF-8 > /etc/locale.gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
locale-gen

# because we are using ssh keys, make sudo not ask for passwords
echo 'root ALL=(ALL) ALL' > /etc/sudoers
echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# I like to use vim :)
echo -e 'EDITOR=vim' >> /etc/environment

# creating the swap file, if you have enough RAM, you can skip this step
fallocate -l "$SWAP_SIZE" /swapfile
chmod 600 /swapfile
mkswap /swapfile
echo /swapfile none swap defaults 0 0 >> /etc/fstab

# auto-complete these essential commands
echo complete -cf sudo >> /etc/bash.bashrc
echo complete -cf man >> /etc/bash.bashrc

# utilities and tools
pacman --noconfirm -S tree git

# xorg + deepin
pacman --noconfirm -S xorg xorg-xinit
pacman --noconfirm -S deepin deepin-extra
pacman --noconfirm -S ttf-freefont

# lightdm
pacman --noconfirm -S lightdm lightdm-gtk-greeter
systemctl enable lightdm

# graphical packages
pacman --noconfirm -S firefox vlc flashplugin

case "$VM_PROVIDER" in
  VMWare)
    pacman --noconfirm -S gtkmm3 open-vm-tools
    pacman --noconfirm -S xf86-video-vmware xf86-input-vmmouse
    systemctl enable vmtoolsd
    ;;
  VirtualBox)
    pacman --noconfirm -S virtualbox-guest-modules-arch virtualbox-guest-utils
    systemctl enable vboxservice
    ;;
esac

# pkgfile
pacman --noconfirm -S pkgfile
systemctl enable pkgfile-update.timer
pkgfile -u

# java development
pacman --noconfirm -S jdk8-openjdk intellij-idea-community-edition
